# Generated by Django 3.2.4 on 2021-07-05 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FireIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_description', models.CharField(max_length=300)),
                ('incident_location', models.CharField(max_length=300)),
                ('incident_date', models.DateTimeField()),
                ('reporter_first_name', models.CharField(max_length=50)),
                ('reporter_last_name', models.CharField(max_length=50)),
                ('reporter_contact_info', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterEmailSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sign_up_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField()),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireapp.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mark_safe', models.BooleanField()),
                ('need', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField()),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireapp.registereduser')),
            ],
        ),
    ]
