# Generated by Django 3.2.4 on 2021-06-17 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='registereduser',
            name='registration_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mark_safe', models.BooleanField()),
                ('need', models.CharField(max_length=300)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireapp.registereduser')),
            ],
        ),
    ]
