# Generated by Django 3.2.4 on 2021-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmailSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sign_up_date', models.DateTimeField()),
            ],
        ),
    ]
