# Generated by Django 3.2.4 on 2021-06-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0002_newsletteremailsub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireincident',
            name='incident_image',
        ),
    ]
