# Generated by Django 3.2.4 on 2021-06-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0002_auto_20210617_0616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
