# Generated by Django 3.2.4 on 2021-07-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0002_auto_20210704_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
