# Generated by Django 3.2.4 on 2021-06-17 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('post_date', models.DateField(default=datetime.datetime.today)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fireapp.registereduser')),
            ],
        ),
    ]
