# Generated by Django 3.2.4 on 2021-06-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0003_remove_fireincident_incident_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremailsub',
            name='sign_up_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
