# Generated by Django 3.2.4 on 2021-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapp', '0005_auto_20210617_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireincident',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
